Add files via upload (#12)
AgilWebProjekt/AgilProjekt pull request #13
Opened 2023-10-11 08:11 UTC by Stephen-Uche

2023-10-11 08:20 UTC, wassimtajeddin approved these changes

2023-10-11 09:14 UTC, RehasLiamsi requested changes

2023-10-11 09:14 UTC, RehasLiamsi commented on AgilProjekt/components/HomePage.vue
Looks good, and a job well done for creating a whole webpage in such a short amount of time. I think you can take away the classes that we won't be needing in the future, and put all the images under a single class. That way it would be easier to style the images.

2023-10-12 11:23 UTC, Stephen-Uche reviewed
I think it's done

2023-10-12 11:29 UTC, closed without merging